server:
  port: 9092

  
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/login-monitor"
      
      
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/olxdb
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate :
        dialect: org.hibernate.dialect.MySQL8Dialect

      
   