server:
  port: 9002
 
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: "/olx-monitor"
  
  endpoint:
    shutdown:
      enabled: true
      
    info:
      enabled: true
      
    health:
      enabled: true
      
      
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/olxdb
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root123
  jpa:
      hibernate.ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect


